[package]
name = "smtp-invoice-io"
version = "0.1.0"
authors = ["cole"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "0.1.22"
native-tls = "0.2.3"
imap = "1.0.2"
mailparse = "0.8.2"